collections:
  methods-playback:
    section: Playback
  methods-files:
    section: Files
  methods-javascript-helpers:
    section: "JavaScript Helpers"
  methods-library:
    section: "Library"

# Build settings
markdown: kramdown